//! KubChain system transaction construction.
//!
//! System transactions are zero-gas transactions injected during block
//! finalization. They are deterministically generated by the consensus
//! layer and are not part of the mempool.
//!
//! # System Transactions
//!
//! | TX | Target | Trigger |
//! |----|--------|---------|
//! | `commitSpan(bytes)` | BKCValidatorSet | `block_number % span == span/2 + 1` |
//! | `slash(address, uint256)` | SlashManager | `difficulty == 1` and signer is official/super |
//! | `distributeReward()` | StakeManager | Every block (if SystemAddress balance > 0) |
//!
//! # Properties
//!
//! - **From:** `header.Coinbase` (block producer)
//! - **GasPrice:** `0`
//! - **Gas:** `u64::MAX / 2` (effectively unlimited)
//! - **Value:** `0` (except distributeReward which sends SystemAddress balance)

use alloy_primitives::{Address, Bytes, U256};
use alloy_sol_types::SolCall;
use kubchain_contracts::abi::{ISlashManager, IStakeManager, IValidatorSet};
use kubchain_primitives::{MinimalVal, Validator};

/// Maximum gas for system transactions (u64::MAX / 2).
///
/// This matches bkc's `math.MaxUint64 / 2` used for system tx gas limit.
pub const SYSTEM_TX_GAS: u64 = u64::MAX / 2;

/// Builds the calldata for a `commitSpan(bytes validatorBytes)` system
/// transaction.
///
/// The `validatorBytes` parameter is an RLP-encoded list of
/// `(address, uint256 votingPower)` tuples representing the next span's
/// validator set.
///
/// # Arguments
///
/// * `validators` - Validators to commit for the next span
///
/// # Returns
///
/// ABI-encoded calldata for the `commitSpan` function.
pub fn build_commit_span_calldata(validators: &[Validator]) -> Bytes {
    // Convert to MinimalVal for RLP encoding
    let minimal_vals: Vec<MinimalVal> = validators.iter().map(MinimalVal::from).collect();

    // RLP-encode the validator list
    let mut rlp_buf = Vec::new();
    alloy_rlp::encode_list(&minimal_vals, &mut rlp_buf);

    // ABI-encode the commitSpan call
    let call = IValidatorSet::commitSpanCall {
        validatorBytes: rlp_buf.into(),
    };
    call.abi_encode().into()
}

/// Builds the calldata for a `slash(address signer, uint256 span)` system
/// transaction.
///
/// # Arguments
///
/// * `spoiled_validator` - Address of the validator who signed out-of-turn
/// * `span_number` - Current span number
///
/// # Returns
///
/// ABI-encoded calldata for the `slash` function.
pub fn build_slash_calldata(spoiled_validator: Address, span_number: U256) -> Bytes {
    let call = ISlashManager::slashCall {
        signer: spoiled_validator,
        span: span_number,
    };
    call.abi_encode().into()
}

/// Builds the calldata for a `distributeReward(uint256 amount, address validator)`
/// system transaction.
///
/// In bkc, the flow is:
/// 1. Read SystemAddress balance
/// 2. Zero out SystemAddress balance
/// 3. Add balance to coinbase
/// 4. Call `distributeReward(balance, coinbase)` on StakeManager with `msg.value = balance`
///
/// # Arguments
///
/// * `amount` - Accumulated fee amount (SystemAddress balance)
/// * `validator` - Block producer address (coinbase)
///
/// # Returns
///
/// ABI-encoded calldata for the `distributeReward` function.
pub fn build_distribute_reward_calldata(amount: U256, validator: Address) -> Bytes {
    let call = IStakeManager::distributeRewardCall {
        amount,
        validator,
    };
    call.abi_encode().into()
}

/// Checks whether a transaction is a system transaction.
///
/// System transactions have the following properties:
/// - Gas price is 0
/// - Sender is the block's coinbase (block producer)
///
/// This is used during block validation to separate user transactions from
/// system transactions.
///
/// Reference: `bkc/consensus/clique/clique.go:268-285` (`IsSystemTransaction`)
pub fn is_system_transaction(
    tx_gas_price: u128,
    tx_sender: &Address,
    block_coinbase: &Address,
) -> bool {
    tx_gas_price == 0 && tx_sender == block_coinbase
}

#[cfg(test)]
mod tests {
    use super::*;
    use alloy_primitives::address;

    #[test]
    fn test_build_commit_span_calldata() {
        let validators = vec![
            Validator {
                address: address!("0x0000000000000000000000000000000000000001"),
                voting_power: U256::from(100),
            },
            Validator {
                address: address!("0x0000000000000000000000000000000000000002"),
                voting_power: U256::from(200),
            },
        ];
        let calldata = build_commit_span_calldata(&validators);
        // Should start with the commitSpan function selector
        assert!(!calldata.is_empty());
        // First 4 bytes are the function selector
        assert!(calldata.len() > 4);
    }

    #[test]
    fn test_build_slash_calldata() {
        let validator = address!("0x0000000000000000000000000000000000000001");
        let span = U256::from(5);
        let calldata = build_slash_calldata(validator, span);
        assert!(!calldata.is_empty());
        assert!(calldata.len() > 4);
    }

    #[test]
    fn test_build_distribute_reward_calldata() {
        let amount = U256::from(1_000_000_000_000_000_000u128); // 1 ETH
        let validator = address!("0x0000000000000000000000000000000000000001");
        let calldata = build_distribute_reward_calldata(amount, validator);
        assert!(!calldata.is_empty());
        assert!(calldata.len() > 4);
    }

    #[test]
    fn test_is_system_transaction() {
        let coinbase = address!("0x0000000000000000000000000000000000000001");
        let other = address!("0x0000000000000000000000000000000000000002");

        // System tx: gas_price == 0 and sender == coinbase
        assert!(is_system_transaction(0, &coinbase, &coinbase));

        // Not system tx: gas_price != 0
        assert!(!is_system_transaction(1, &coinbase, &coinbase));

        // Not system tx: sender != coinbase
        assert!(!is_system_transaction(0, &other, &coinbase));
    }

    #[test]
    fn test_system_tx_gas_constant() {
        assert_eq!(SYSTEM_TX_GAS, u64::MAX / 2);
        assert!(SYSTEM_TX_GAS > 0);
    }
}
